<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>KitLugia.Plugin.Example</RootNamespace>
    <AssemblyName>KitLugia.Plugin.Example</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KitLugia.Core\KitLugia.Core.csproj" />
  </ItemGroup>

  <!-- Copia a DLL do plugin para a pasta Plugins do output do GUI (debug/release) -->
  <Target Name="CopyToKitPlugins" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\..\..\KitLugia.GUI\bin\$(Configuration)\$(TargetFramework)\Plugins"/>
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)\..\..\KitLugia.GUI\bin\$(Configuration)\$(TargetFramework)\Plugins" SkipUnchangedFiles="true"/>
  </Target>

</Project>
