using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.Versioning;

namespace KitLugia.Core
{
    [SupportedOSPlatform("windows")]
    public static class EmergencyUEFIManager
    {
        private const string EFI_SRC_DIR = @"Resources\KitLugiaEFI";
        private const string ESP_KITLUGIA_DIR = @"EFI\KitLugia";
        private const string ESP_REFIND_DIR = @"EFI\refind";
        private const string MARKER_FILE = "kitlugia_done.txt";
        private const string NEW_PARTITION_LABEL = "KITLUGIA";

        /*
         * === DEPLOY LOG ===
         * 2026-05-30 — v1.0: Initial EmergencyUEFIManager
         *   - Builds/copies kitlugia_shrink.efi to ESP
         *   - Generates kitlugia.conf with shrink parameters
         *   - Configures rEFInd for auto-boot
         *   - Prepares ESP structure (EFI/KitLugia/)
         *   - Reboots system
         *
         *  vNEXT:
         *   - Build from source via toolchain build scripts
         *   - Add fallback if kitlugia_shrink.efi not pre-built
         *   - Support directly embedding in PE as resource
         */

        public static async Task<(bool Success, string Message)> DeployAsync(
            int diskIndex,
            int partitionIndex,
            long partitionSizeBytes,
            string driveLetter,
            long shrinkSizeMb,
            string newPartitionLabel,
            Action<double, string>? progressCallback = null)
        {
            try
            {
                progressCallback?.Invoke(5, "Montando ESP...");
                string? espDrive = await MountEspAsync();
                if (espDrive == null)
                    return (false, "Não foi possível montar a partição ESP.");

                string baseDir = AppDomain.CurrentDomain.BaseDirectory;
                string srcEfiFile = Path.Combine(baseDir, EFI_SRC_DIR, "bin", "kitlugia_shrink.efi");

                if (!File.Exists(srcEfiFile))
                {
                    await DismountEspAsync(espDrive);
                    return (false,
                        $"kitlugia_shrink.efi não encontrado em:\n{srcEfiFile}\n\n" +
                        "Execute build_toolchain.sh (WSL) ou build_toolchain.ps1 (MSYS2) primeiro.");
                }

                // ---- Step 1: Create ESP dirs ----
                progressCallback?.Invoke(15, "Preparando diretórios no ESP...");
                string kitlugiaEspDir = Path.Combine(espDrive, ESP_KITLUGIA_DIR);
                string refindEspDir = Path.Combine(espDrive, ESP_REFIND_DIR);
                Directory.CreateDirectory(kitlugiaEspDir);

                // ---- Step 2: Copy EFI app ----
                progressCallback?.Invoke(30, "Copiando kitlugia_shrink.efi...");
                string destEfi = Path.Combine(kitlugiaEspDir, "kitlugia_shrink.efi");
                File.Copy(srcEfiFile, destEfi, true);
                Logger.Log($"[UEFI] EFI app copiado para {destEfi}");

                // ---- Step 3: Generate kitlugia.conf ----
                progressCallback?.Invoke(45, "Gerando kitlugia.conf...");
                string dl = driveLetter.Replace(":", "");
                string configPath = Path.Combine(espDrive, "kitlugia.conf");
                string configContent = $@"# KitLugia shrink config
# Auto-generated by EmergencyUEFIManager
disk={diskIndex}
partition={partitionIndex}
shrink_mb={shrinkSizeMb}
label={NEW_PARTITION_LABEL}
";
                File.WriteAllText(configPath, configContent, Encoding.ASCII);
                Logger.Log($"[UEFI] Config escrito em {configPath}");

                // ---- Step 4: Install KitLugia rEFInd fork (if available) ----
                progressCallback?.Invoke(60, "Instalando KitLugia rEFInd fork...");
                bool refindForkDeployed = await InstallRefindFork(espDrive);

                // ---- Step 5: Configure rEFInd ----
                progressCallback?.Invoke(65, "Configurando rEFInd...");
                bool refindOk = refindForkDeployed
                    ? true  // Fork has KitLugia built-in, no config needed
                    : await SetupRefindAutoBoot(espDrive);

                // ---- Step 6: Unmount ESP ----
                progressCallback?.Invoke(80, "Finalizando...");
                await DismountEspAsync(espDrive);

                string bootMsg;
                if (refindForkDeployed)
                    bootMsg = "KitLugia rEFInd fork implantado — entry KitLugia Recovery built-in (sem config necessária).";
                else if (refindOk)
                    bootMsg = "rEFInd configurado para boot automático do KitLugia Recovery.";
                else
                    bootMsg = "rEFInd não encontrado. Ao reiniciar, selecione manualmente 'KitLugia Recovery' no menu do rEFInd.";

                Logger.Log($"[UEFI] Deploy concluído. {bootMsg}");

                return (true,
                    $"Ambiente UEFI implantado com sucesso!\n\n" +
                    $"Operação: Reduzir {dl}: em {shrinkSizeMb}MB, criar partição {NEW_PARTITION_LABEL}\n\n" +
                    $"{bootMsg}\n\n" +
                    $"⚠️ O sistema será reiniciado para o KitLugia Shrink EFI.");
            }
            catch (Exception ex)
            {
                Logger.Log($"[UEFI] ERRO: {ex.Message}");
                return (false, $"Erro ao implantar ambiente UEFI: {ex.Message}");
            }
        }

        private static async Task<bool> SetupRefindAutoBoot(string espDrive)
        {
            string refindConfPath = Path.Combine(espDrive, ESP_REFIND_DIR, "refind.conf");
            string refindBackup = Path.Combine(espDrive, ESP_REFIND_DIR, "refind.conf.kitlugia_backup");

            if (!File.Exists(refindConfPath))
            {
                Logger.Log("[UEFI] rEFInd não encontrado no ESP.");
                return false;
            }

            if (!File.Exists(refindBackup))
                File.Copy(refindConfPath, refindBackup);

            string customConfig = $@"# KitLugia Emergency — auto-generated
timeout         0
default_selection  ""KitLugia Recovery""
hideui          hints,label,badges,banner
dont_scan_files refind_x64.efi,bootmgfw.original.efi,mmx64.efi,grubx64.efi,shellx64.efi,BOOTX64.EFI
dont_scan_volumes ""SYSTEM"",""RECOVERY""
showtools       reboot,shutdown

menuentry ""KitLugia Recovery"" {{
    loader   \EFI\KitLugia\kitlugia_shrink.efi
    ostype   Linux
}}

menuentry ""Windows"" {{
    loader   \EFI\Microsoft\Boot\bootmgfw.efi
    ostype   Windows
}}
";
            await File.WriteAllTextAsync(refindConfPath, customConfig, Encoding.UTF8);
            Logger.Log("[UEFI] rEFInd configurado para auto-boot KitLugia Recovery.");
            return true;
        }

        public static async Task<bool> IsPreBootCompleted()
        {
            try
            {
                string? espDrive = await MountEspAsync();
                if (espDrive == null) return false;

                string markerPath = Path.Combine(espDrive, MARKER_FILE);
                bool exists = File.Exists(markerPath);

                await DismountEspAsync(espDrive);

                if (exists)
                {
                    Logger.Log("[UEFI] Marcador de conclusão encontrado no ESP!");
                    // Also verify the KITLUGIA partition exists
                    string result = await Task.Run(() =>
                    {
                        using var ps = new System.Diagnostics.Process();
                        ps.StartInfo.FileName = "powershell";
                        ps.StartInfo.Arguments =
                            "-Command \"Get-Partition | Where-Object { $_.PartitionNumber -gt 0 } | " +
                            "Get-Volume | Where-Object { $_.FileSystemLabel -eq '" + NEW_PARTITION_LABEL + "' } | " +
                            "Select-Object -First 1 | Format-Table -AutoSize\"";
                        ps.StartInfo.UseShellExecute = false;
                        ps.StartInfo.RedirectStandardOutput = true;
                        ps.StartInfo.CreateNoWindow = true;
                        ps.Start();
                        string output = ps.StandardOutput.ReadToEnd();
                        ps.WaitForExit(10000);
                        return output;
                    });
                    return result.Trim().Length > 0;
                }

                return false;
            }
            catch (Exception ex)
            {
                Logger.Log($"[UEFI] Erro ao verificar conclusão: {ex.Message}");
                return false;
            }
        }

        public static async Task<(bool Success, string Message)> CleanupAsync()
        {
            try
            {
                string? espDrive = await MountEspAsync();
                if (espDrive == null)
                    return (false, "Não foi possível montar ESP para limpeza.");

                // Restore rEFInd fork backup (binary)
                string refindDir = Path.Combine(espDrive, ESP_REFIND_DIR);
                string refindBak = Path.Combine(refindDir, "refind_x64.efi.kitlugia_bak");
                string refindEfi = Path.Combine(refindDir, "refind_x64.efi");
                if (File.Exists(refindBak))
                {
                    File.Copy(refindBak, refindEfi, true);
                    File.Delete(refindBak);
                    Logger.Log("[UEFI] rEFInd binary restaurado do backup.");
                }

                // Restore rEFInd config
                string refindConfBackup = Path.Combine(refindDir, "refind.conf.kitlugia_backup");
                string refindConf = Path.Combine(refindDir, "refind.conf");
                if (File.Exists(refindConfBackup))
                {
                    if (File.Exists(refindConf))
                        File.Delete(refindConf);
                    File.Move(refindConfBackup, refindConf);
                    Logger.Log("[UEFI] rEFInd config restaurada.");
                }

                // Remove kitlugia marker
                string markerPath = Path.Combine(espDrive, MARKER_FILE);
                if (File.Exists(markerPath)) File.Delete(markerPath);

                // Remove kitlugia.conf
                string cfgPath = Path.Combine(espDrive, "kitlugia.conf");
                if (File.Exists(cfgPath)) File.Delete(cfgPath);

                // Remove KitLugia EFI dir
                string kitlugiaEspDir = Path.Combine(espDrive, ESP_KITLUGIA_DIR);
                if (Directory.Exists(kitlugiaEspDir))
                    Directory.Delete(kitlugiaEspDir, true);

                await DismountEspAsync(espDrive);
                Logger.Log("[UEFI] Cleanup concluído.");
                return (true, "Ambiente UEFI limpo e rEFInd restaurado.");
            }
            catch (Exception ex)
            {
                Logger.Log($"[UEFI] Erro no cleanup: {ex.Message}");
                return (false, $"Erro na limpeza: {ex.Message}");
            }
        }

        private static async Task<bool> InstallRefindFork(string espDrive)
        {
            // Try to deploy the KitLugia rEFInd fork (custom binary)
            string baseDir = AppDomain.CurrentDomain.BaseDirectory;
            string forkEfi = Path.Combine(baseDir, EFI_SRC_DIR, "refind_fork", "bin", "refind_x64.efi");
            string refindDir = Path.Combine(espDrive, ESP_REFIND_DIR);

            if (!File.Exists(forkEfi))
            {
                Logger.Log("[UEFI] rEFInd fork não encontrado; usando rEFInd existente.");
                return false;
            }

            try
            {
                // Backup existing rEFInd
                string existingRefind = Path.Combine(refindDir, "refind_x64.efi");
                string backupRefind = Path.Combine(refindDir, "refind_x64.efi.kitlugia_bak");
                if (File.Exists(existingRefind) && !File.Exists(backupRefind))
                    File.Copy(existingRefind, backupRefind);

                // Copy forked rEFInd
                Directory.CreateDirectory(refindDir);
                File.Copy(forkEfi, existingRefind, true);

                // Copy KitLugia icons
                string iconsDir = Path.Combine(refindDir, "icons");
                Directory.CreateDirectory(iconsDir);
                string iconSrc = Path.Combine(baseDir, EFI_SRC_DIR, "refind_fork", "icons", "tool_kitlugia.png");
                if (File.Exists(iconSrc))
                    File.Copy(iconSrc, Path.Combine(iconsDir, "tool_kitlugia.png"), true);
                string iconBanner = Path.Combine(baseDir, EFI_SRC_DIR, "refind_fork", "icons", "banner_kitlugia.png");
                if (File.Exists(iconBanner))
                    File.Copy(iconBanner, Path.Combine(refindDir, "banner.png"), true);

                Logger.Log("[UEFI] KitLugia rEFInd fork implantado com sucesso.");
                return true;
            }
            catch (Exception ex)
            {
                Logger.Log($"[UEFI] Falha ao instalar rEFInd fork: {ex.Message}");
                return false;
            }
        }

        public static async Task TriggerReboot()
        {
            Logger.Log("[UEFI] Reiniciando para KitLugia Shrink EFI...");
            await RunProcessCaptured("shutdown", "/r /t 5 /c \"KitLugia: Reiniciando para KitLugia EFI Recovery\"", 10000);
        }

        private static async Task<string?> MountEspAsync()
        {
            for (char letter = 'S'; letter <= 'Z'; letter++)
            {
                string drive = $"{letter}:";
                try { if (new DriveInfo(drive).IsReady) continue; } catch { Logger.LogWarning("Unknown", "Exception suppressed"); }

                var (exit, _) = await RunProcessCaptured("mountvol", $"{drive} /S");
                if (exit != 0) continue;

                if (Directory.Exists($"{drive}\\EFI"))
                {
                    Logger.Log($"[UEFI] ESP montada em {drive}");
                    return drive;
                }
            }
            Logger.Log("[UEFI] AVISO: Nenhuma letra disponível para montar o ESP.");
            return null;
        }

        private static async Task DismountEspAsync(string drive)
        {
            await RunProcessCaptured("mountvol", $"{drive} /D");
        }

        private static async Task<(int ExitCode, string Output)> RunProcessCaptured(
            string filename, string args, int timeoutMs = 60000)
        {
            try
            {
                using var proc = new System.Diagnostics.Process();
                proc.StartInfo.FileName = filename;
                proc.StartInfo.Arguments = args;
                proc.StartInfo.UseShellExecute = false;
                proc.StartInfo.RedirectStandardOutput = true;
                proc.StartInfo.RedirectStandardError = true;
                proc.StartInfo.CreateNoWindow = true;

                var outputBuilder = new StringBuilder();
                var errorBuilder = new StringBuilder();
                using var outputWaitHandle = new System.Threading.ManualResetEvent(false);
                using var errorWaitHandle = new System.Threading.ManualResetEvent(false);

                proc.OutputDataReceived += (sender, e) =>
                {
                    if (e.Data == null) outputWaitHandle.Set();
                    else outputBuilder.AppendLine(e.Data);
                };
                proc.ErrorDataReceived += (sender, e) =>
                {
                    if (e.Data == null) errorWaitHandle.Set();
                    else errorBuilder.AppendLine(e.Data);
                };

                proc.Start();
                proc.BeginOutputReadLine();
                proc.BeginErrorReadLine();

                if (!proc.WaitForExit(timeoutMs))
                {
                    try { proc.Kill(entireProcessTree: true); } catch { Logger.LogWarning("Unknown", "Exception suppressed"); }
                    return (-1, "TIMEOUT");
                }

                proc.WaitForExitAsync().Wait(timeoutMs);
                outputWaitHandle.WaitOne(timeoutMs);
                errorWaitHandle.WaitOne(timeoutMs);

                string output = outputBuilder.ToString().Trim();
                string error = errorBuilder.ToString().Trim();
                if (!string.IsNullOrEmpty(error)) output += "\n" + error;

                return (proc.ExitCode, output);
            }
            catch (Exception ex)
            {
                return (-1, ex.Message);
            }
        }
    }
}
