using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace KitLugia.Core
{
    public static class KnownStartupArgs
    {
        private static readonly Dictionary<string, string[]> KnownArgs = new(StringComparer.OrdinalIgnoreCase)
        {
            ["discord"] = new[] { "--start-minimized", "--silent-restart" },
            ["steam"] = new[] { "-silent", "-login" },
            ["spotify"] = new[] { "--minimize" },
            ["slack"] = new[] { "--startup" },
            ["telegram"] = new[] { "-startintray" },
            ["dropbox"] = new[] { "--minimize" },
            ["onedrive"] = new[] { "/background" },
            ["itunes"] = new[] { "/minimized" },
            ["utorrent"] = new[] { "-MINIMIZED" },
            ["qbittorrent"] = new[] { "--no-splash" },
            ["brave"] = new[] { "--silent-launch" },
            ["chrome"] = new[] { "--no-startup-window", "--silent-launch" },
            ["firefox"] = new[] { "--silent" },
            ["edge"] = new[] { "--no-startup-window" },
            ["notion"] = new[] { "--disable-auto-update" },
            ["obsidian"] = new[] { "--disable-auto-update" },
            ["code"] = new[] { "--disable-updates" },
            ["docker desktop"] = new[] { "--windows-containers" },
            ["nvidia"] = new[] { "--silent" },
            ["amd"] = new[] { "--silent" },
            ["everything"] = new[] { "-startup" },
            ["translucenttb"] = new[] { "--startup" },
            ["autohotkey"] = new[] { "/silent" },
            ["signalrgb"] = new[] { "--silent" },
            ["obs studio"] = new[] { "--minimize-to-tray", "--disable-shutdown-check" },
            ["sumatrapdf"] = new[] { "-silent" },
            ["greenshot"] = new[] { "-silent" },
            ["sharex"] = new[] { "-silent" },
            ["powertoys"] = new[] { "--startup" },
            ["thunderbird"] = new[] { "-silent" },
            ["skype"] = new[] { "--start-minimized", "/minimized" },
            ["zoom"] = new[] { "--silent" },
            ["whatsapp"] = new[] { "--startup" },
            ["deezer"] = new[] { "--minimize" },
            ["pycharm"] = new[] { "--disable-auto-update" },
            ["intellij"] = new[] { "--disable-auto-update" },
            ["unity hub"] = new[] { "--no-updates" },
            ["epic games"] = new[] { "-silent" },
            ["gog galaxy"] = new[] { "--silent" },
            ["battle.net"] = new[] { "--exec=" },
            ["riot client"] = new[] { "--launch-product=valorant" },
            ["origin"] = new[] { "/silent" },
            ["xbox"] = new[] { "--silent" },
            ["microsoft teams"] = new[] { "--startup" },
            ["outlook"] = new[] { "/background" },
            ["raycast"] = new[] { "--silent-restart" },
            ["vlc"] = new[] { "--intf", "--no-playlist-enqueue", "--no-qt-fs-controller" },
            ["7zfm"] = new[] { "--startup" },
            ["winrar"] = new[] { "--startup" },
            ["keepass"] = new[] { "--silent", "--minimize" },
            ["bitwarden"] = new[] { "--silent" },
            ["lastpass"] = new[] { "--silent" },
            ["1password"] = new[] { "--silent" },
            ["protonmail"] = new[] { "--silent" },
            ["thunderbird"] = new[] { "-silent" },
            ["postman"] = new[] { "--disable-auto-update" },
            ["insomnia"] = new[] { "--startup" },
            ["cmder"] = new[] { "--startup" },
            ["windows terminal"] = new[] { "--startup" },
            ["alacritty"] = new[] { "--startup" },
            ["mobaxterm"] = new[] { "--startup" },
            ["putty"] = new[] { "-silent" },
            ["winscp"] = new[] { "--startup" },
            ["filezilla"] = new[] { "--startup" },
            ["cyberduck"] = new[] { "--startup" },
            ["rider"] = new[] { "--disable-auto-update" },
            ["webstorm"] = new[] { "--disable-auto-update" },
            ["goland"] = new[] { "--disable-auto-update" },
            ["datagrip"] = new[] { "--disable-auto-update" },
            ["android studio"] = new[] { "--disable-auto-update" },
            ["eclipse"] = new[] { "-startup" },
            ["netbeans"] = new[] { "--startup" },
            ["vmware"] = new[] { "--silent" },
            ["virtualbox"] = new[] { "--startup" },
            ["docker"] = new[] { "--windows-containers" },
            ["kubernetes"] = new[] { "--startup" },
            ["minikube"] = new[] { "--startup" },
            ["sourcetree"] = new[] { "--startup" },
            ["github desktop"] = new[] { "--silent" },
            ["gitkraken"] = new[] { "--startup" },
            ["sublime text"] = new[] { "--background" },
            ["atom"] = new[] { "--background" },
            ["vim"] = new[] { "--startup" },
            ["neovim"] = new[] { "--startup" },
            ["emacs"] = new[] { "--startup" },
            ["notepad++"] = new[] { "--startup" },
            ["notepad2"] = new[] { "--startup" },
            ["notepad3"] = new[] { "--startup" },
            ["evernote"] = new[] { "--startup" },
            ["notion"] = new[] { "--disable-auto-update" },
            ["obsidian"] = new[] { "--disable-auto-update" },
            ["logseq"] = new[] { "--startup" },
            ["roam research"] = new[] { "--startup" },
            ["trello"] = new[] { "--startup" },
            ["asana"] = new[] { "--startup" },
            ["todoist"] = new[] { "--startup" },
            ["clickup"] = new[] { "--startup" },
            ["notion calendar"] = new[] { "--startup" },
            ["microsoft todo"] = new[] { "--startup" },
            ["weather"] = new[] { "--startup" },
            ["clock"] = new[] { "--startup" },
            ["alarms"] = new[] { "--startup" },
            ["sticky notes"] = new[] { "--startup" },
            ["snipping tool"] = new[] { "--startup" },
            ["power automate"] = new[] { "--startup" },
            ["power bi"] = new[] { "--startup" },
            ["teams"] = new[] { "--startup" },
            ["microsoft edge"] = new[] { "--no-startup-window" },
            ["google chrome"] = new[] { "--no-startup-window", "--silent-launch" },
            ["chromium"] = new[] { "--no-startup-window", "--silent-launch" },
            ["opera"] = new[] { "--no-startup-window" },
            ["brave"] = new[] { "--silent-launch" },
            ["vivaldi"] = new[] { "--silent-launch" },
            ["tor browser"] = new[] { "--silent" },
            ["waterfox"] = new[] { "--silent" },
            ["pale moon"] = new[] { "--silent" },
            ["irfanview"] = new[] { "--startup" },
            ["xnview"] = new[] { "--startup" },
            ["nomacs"] = new[] { "--startup" },
            ["honeyview"] = new[] { "--startup" },
            ["imageglass"] = new[] { "--startup" },
            ["paint.net"] = new[] { "--startup" },
            ["gimp"] = new[] { "--startup" },
            ["inkscape"] = new[] { "--startup" },
            ["krita"] = new[] { "--startup" },
            ["blender"] = new[] { "--startup" },
            ["unity"] = new[] { "--disable-auto-update" },
            ["unreal engine"] = new[] { "--disable-auto-update" },
            ["godot"] = new[] { "--startup" },
            ["fmod"] = new[] { "--startup" },
            ["audacity"] = new[] { "--startup" },
            ["reaper"] = new[] { "--startup" },
            ["ableton"] = new[] { "--startup" },
            ["fl studio"] = new[] { "--startup" },
            ["cubase"] = new[] { "--startup" },
            ["spotify"] = new[] { "--minimize" },
            ["tidal"] = new[] { "--startup" },
            ["apple music"] = new[] { "--startup" },
            ["youtube music"] = new[] { "--startup" },
            ["plex"] = new[] { "--startup" },
            ["jellyfin"] = new[] { "--startup" },
            ["emby"] = new[] { "--startup" },
            ["kodi"] = new[] { "--startup" },
            ["stremio"] = new[] { "--startup" },
            ["popcorn time"] = new[] { "--startup" },
            ["netflix"] = new[] { "--startup" },
            ["prime video"] = new[] { "--startup" },
            ["hbo max"] = new[] { "--startup" },
            ["disney+"] = new[] { "--startup" },
            ["crunchyroll"] = new[] { "--startup" },
            ["funimation"] = new[] { "--startup" },
            ["hidemy name"] = new[] { "--startup" },
            ["nordvpn"] = new[] { "--silent" },
            ["expressvpn"] = new[] { "--silent" },
            ["protonvpn"] = new[] { "--silent" },
            ["cloudflare warp"] = new[] { "--startup" },
            ["tailscale"] = new[] { "--startup" },
            ["zerotier"] = new[] { "--startup" },
            ["hamachi"] = new[] { "--startup" },
            ["teamviewer"] = new[] { "--silent" },
            ["anydesk"] = new[] { "--silent" },
            ["splashtop"] = new[] { "--startup" },
            ["chrome remote desktop"] = new[] { "--startup" },
            ["parsec"] = new[] { "--startup" },
            ["moonlight"] = new[] { "--startup" },
            ["sunshine"] = new[] { "--startup" },
            ["steam"] = new[] { "-silent", "-login" },
            ["epic games launcher"] = new[] { "-silent" },
            ["gog galaxy"] = new[] { "--silent" },
            ["ubisoft connect"] = new[] { "--silent" },
            ["origin"] = new[] { "/silent" },
            ["battle.net"] = new[] { "--exec=" },
            ["riot client"] = new[] { "--launch-product=" },
            ["discord"] = new[] { "--start-minimized", "--silent-restart" },
            ["skype"] = new[] { "--start-minimized", "/minimized" },
            ["telegram"] = new[] { "-startintray" },
            ["signal"] = new[] { "--start-in-tray" },
            ["whatsapp"] = new[] { "--startup" },
            ["slack"] = new[] { "--startup" },
            ["microsoft teams"] = new[] { "--startup" },
            ["zoom"] = new[] { "--silent" },
            ["webex"] = new[] { "--silent" },
            ["google meet"] = new[] { "--startup" },
            ["element"] = new[] { "--startup" },
            ["matrix"] = new[] { "--startup" },
            ["riot.im"] = new[] { "--startup" },
            ["f.lux"] = new[] { "--startup" },
            ["lightbulb"] = new[] { "--startup" },
            ["twinkle tray"] = new[] { "--startup" },
            ["careueyes"] = new[] { "--startup" },
            ["eyecare"] = new[] { "--startup" },
            ["microsoft defender"] = new[] { "--startup" },
            ["malwarebytes"] = new[] { "--silent" },
            ["bitdefender"] = new[] { "--silent" },
            ["kaspersky"] = new[] { "--silent" },
            ["avast"] = new[] { "--silent" },
            ["avg"] = new[] { "--silent" },
            ["norton"] = new[] { "--silent" },
            ["mcafee"] = new[] { "--silent" },
            ["eset"] = new[] { "--silent" },
            ["comodo"] = new[] { "--silent" },
            ["glasswire"] = new[] { "--startup" },
            ["wireshark"] = new[] { "--startup" },
            ["fiddler"] = new[] { "--startup" },
            ["postman agent"] = new[] { "--startup" },
            ["insomnia agent"] = new[] { "--startup" },
            ["obs studio"] = new[] { "--minimize-to-tray", "--disable-shutdown-check" },
            ["streamlabs"] = new[] { "--startup" },
            ["xsplit"] = new[] { "--startup" },
            ["twitch studio"] = new[] { "--startup" },
            ["voicemeeter"] = new[] { "--startup" },
            ["voicemeeter banana"] = new[] { "--startup" },
            ["voicemeeter potato"] = new[] { "--startup" },
            ["ear trumpet"] = new[] { "--startup" },
            ["sonic"] = new[] { "--startup" },
            ["midi"] = new[] { "--startup" },
        };

        public static string[]? SuggestArgs(string exePathOrName)
        {
            if (string.IsNullOrWhiteSpace(exePathOrName)) return null;

            string name = Path.GetFileNameWithoutExtension(exePathOrName)?.Trim() ?? "";

            if (KnownArgs.TryGetValue(name, out var args)) return args;

            foreach (var kvp in KnownArgs)
            {
                if (name.IndexOf(kvp.Key, StringComparison.OrdinalIgnoreCase) >= 0)
                    return kvp.Value;
            }

            return null;
        }

        public static string[]? SuggestArgsForCommand(string fullCommand)
        {
            if (string.IsNullOrWhiteSpace(fullCommand)) return null;
            StartupManager.ExtractCommandParts(fullCommand, out string? path, out _);
            return SuggestArgs(path ?? fullCommand);
        }
    }
}
